services:
  backend:
    build:
      context: ./todo-api-nest
      dockerfile: Dockerfile.dev
    container_name: nestjs_backend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-api-nest:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - PORT=3000
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=todo-db
      - MONGO_URI=mongodb://mongo-db:27017/todo-db
    depends_on:
      - mongo-db
    networks:
      - todoProyect
    restart: always
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todoProyect
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo-db
    networks:
      - todoProyect
    restart: always

  frontend:
    build: ./frontendTodoVue
    container_name: vue_frontend
    ports:
      - "8080:5173"
    volumes:
      - ./frontendTodoVue:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - todoProyect
    restart: always

volumes:
  mongo_data:

networks:
  todoProyect:
    external: true
